package com.timur.ewa.app.presentation.ui.teams

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment
import androidx.recyclerview.widget.LinearLayoutManager
import com.timur.ewa.app.data.model.FootballTeam
import com.timur.ewa.app.databinding.FragmentTeamsBinding

class TeamsFragment : Fragment() {

    private lateinit var binding: FragmentTeamsBinding

    val teams = listOf(
        FootballTeam("Manchester City", "https://d3d71ba2asa5oz.cloudfront.net/62001271/images/04108_sv1.jpg", "Founded in 1880 as St. Mark's, Manchester City has evolved into one of the most successful clubs in English football. With 8 league titles, including a remarkable treble in 2023, City is known for its attacking style of play, particularly under manager Pep Guardiola. The team boasts a wealth of talent, including stars like Kevin De Bruyne and Erling Haaland. The Etihad Stadium provides an electric atmosphere for fans, and the club's recent success in domestic and European competitions has solidified its place among the elite. City's financial backing and commitment to youth development have transformed them into a powerhouse, making them a formidable force in modern football."),

        FootballTeam("Liverpool", "https://avatars.mds.yandex.net/i?id=0775029b0046819e410d3a7ed1d03780-4956126-images-thumbs&n=13", "Liverpool Football Club, founded in 1892, is one of the most storied clubs in football history, with 19 league titles and 6 UEFA Champions League trophies. Known for their passionate fan base, Liverpool's Anfield stadium is famous for its iconic 'You'll Never Walk Alone' anthem. Under the management of Jürgen Klopp, the team has embraced an exciting attacking style, highlighted by the likes of Mohamed Salah and Sadio Mané. The club's rich heritage includes legendary figures such as Bill Shankly and Bob Paisley, who shaped its identity. Liverpool's fierce rivalry with Manchester United adds to the drama of the Premier League, making every encounter a must-watch event."),

        FootballTeam("Real Madrid", "https://i.pinimg.com/originals/56/09/e1/5609e13ac8181f607d7083d59663ddcc.jpg", "Real Madrid, established in 1902, is synonymous with success in football, boasting an impressive 35 La Liga titles and a record 14 UEFA Champions League trophies. The club is known for its galáctico philosophy, attracting world-class talent like Cristiano Ronaldo, Zinedine Zidane, and Karim Benzema. The Santiago Bernabéu Stadium is a fortress, providing a breathtaking atmosphere for fans. Real Madrid's fierce rivalry with Barcelona, known as El Clásico, is one of the most anticipated matches in the world. The club's commitment to excellence and its rich history make it a symbol of prestige in the footballing world."),

        FootballTeam("Barcelona", "https://cdn.kibrispdr.org/data/1064/download-logo-barcelona-vektor-7.jpg", "Founded in 1899, FC Barcelona is renowned for its attacking style and commitment to youth development through its famed La Masia academy. With 26 La Liga titles and 5 UEFA Champions League trophies, the club has produced legendary players such as Lionel Messi, Xavi, and Andrés Iniesta. The Camp Nou, one of the largest stadiums in Europe, is a sanctuary for fans. Barcelona's rivalry with Real Madrid is celebrated worldwide, with El Clásico capturing the attention of millions. The club's ethos of 'Més que un club' emphasizes its cultural significance in Catalonia and beyond, making it a beloved institution in global football."),

        FootballTeam("Bayern Munich", "https://i.pinimg.com/736x/75/9f/fa/759ffa6793fde2fee83216d8bfabcdc1--fc-bayern-munich-logo-football.jpg", "Bayern Munich, founded in 1900, is the most successful club in German football history, with 31 Bundesliga titles and 6 UEFA Champions League trophies. Known for their relentless attacking play, Bayern has been home to legends such as Franz Beckenbauer, Gerd Müller, and more recently, Robert Lewandowski. The Allianz Arena, with its iconic illuminated facade, is a fortress for the team's passionate supporters. Bayern's dominance in the Bundesliga is complemented by their consistent performances in Europe, making them a perennial contender. The club's commitment to excellence and youth development ensures its place at the forefront of global football."),

        FootballTeam("Manchester United", "https://i.pinimg.com/originals/1f/7f/09/1f7f09801fa9bacd049ada1587246edc.png", "Manchester United, founded in 1878, is one of the most iconic football clubs in the world, with a rich history of 20 league titles and 3 UEFA Champions League trophies. The club's legendary manager Sir Alex Ferguson transformed United into a global brand during his tenure. Old Trafford, known as the 'Theatre of Dreams,' is a fortress for fans. The club has produced numerous footballing greats, including George Best, Eric Cantona, and Ryan Giggs. United's fierce rivalry with Liverpool adds to the drama of the Premier League, making every encounter a highly anticipated event. Despite recent challenges, the club's rich heritage and passionate fan base remain a source of pride."),

        FootballTeam("Paris Saint-Germain", "https://i0.wp.com/icdn.psgtalk.com/wp-content/uploads/2020/03/PSG-logo-2002-2013.jpg?ssl=1", "Founded in 1970, Paris Saint-Germain (PSG) has rapidly risen to prominence in French football, winning 10 Ligue 1 titles, including seven in the last decade. The club's rise can be attributed to significant financial backing, allowing it to attract world-class talent like Neymar, Kylian Mbappé, and Lionel Messi. The Parc des Princes serves as a vibrant home ground for the team's passionate supporters. PSG's style of play emphasizes attacking football, making them a force in domestic competitions and a contender in Europe. The club's ambition to secure its first UEFA Champions League title is a driving force behind its growth, and it has become a symbol of modern football in France."),

        FootballTeam("Juventus", "https://avatars.mds.yandex.net/i?id=3182a1fb9db8ad587a80388f08051eec_l-5216657-images-thumbs&n=13", "Juventus, founded in 1897, is one of the most successful clubs in Italian football history, with 36 Serie A titles and 2 UEFA Champions League trophies. Known for their strong defensive play, the club has a rich heritage of legendary players, including Alessandro Del Piero and Michel Platini. The Allianz Stadium is a modern arena that provides a fantastic atmosphere for fans. Juventus's fierce rivalry with AC Milan is a highlight of Serie A, known as the Derby d'Italia. The club's commitment to excellence and consistent performances in both domestic and European competitions solidify its status as a powerhouse in football."),

        FootballTeam("Chelsea", "https://avatars.mds.yandex.net/i?id=a71a2d97dfd476fb939ac2f363ec441c_l-8314096-images-thumbs&n=13", "Founded in 1905, Chelsea FC has emerged as one of the top clubs in English football, boasting 6 league titles and 2 UEFA Champions League trophies. The club's success surged in the 2000s under the ownership of Roman Abramovich, attracting world-class players and managers. Stamford Bridge, the club's home ground, provides a vibrant atmosphere for fans. Chelsea's rivalry with London clubs, particularly Arsenal and Tottenham, adds to the excitement of the Premier League. The team's attacking style and commitment to playing attractive football have made them a favorite among supporters. Chelsea's ambition remains high as they strive for continued success on both domestic and European fronts."),

        FootballTeam("Inter Milan", "https://img.championat.com/i/p/z/1655471953940261043.png", "Inter Milan, founded in 1908, is one of the most successful clubs in Italian football, boasting 19 Serie A titles and 3 UEFA Champions League trophies. Known for their blue and black striped jerseys, the club has a passionate fan base. Inter's historic rivalry with AC Milan, known as the Derby della Madonnina, is one of the fiercest in football, captivating fans and players alike. The club's recent success includes winning Serie A in 2021, ending Juventus's dominance. With a rich heritage of legendary players like Javier Zanetti and Ronaldo, Inter continues to compete at the highest levels, aiming for more domestic and European glory."),

        FootballTeam("AC Milan", "https://i.pinimg.com/736x/7b/8f/ed/7b8fedf6bf8db0c56514d731e0e04ac2.jpg", "AC Milan, founded in 1899, is one of the most storied clubs in football history, boasting 18 Serie A titles and 7 UEFA Champions League trophies. Known for their iconic red and black stripes, the club has produced legendary players such as Franco Baresi, Paolo Maldini, and Marco van Basten. The San Siro stadium serves as a fortress for the club's passionate supporters. AC Milan's rivalry with Inter, known as the Derby della Madonnina, adds to the excitement of Serie A. The club has a rich heritage and a commitment to excellence, striving for a return to its former glory in both domestic and European competitions."),

        FootballTeam("Borussia Dortmund", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/1024px-Borussia_Dortmund_logo.svg.png", "Borussia Dortmund, founded in 1909, is one of the most successful clubs in German football, with 8 Bundesliga titles and 1 UEFA Champions League trophy. The club is renowned for its passionate fan base, known as the 'Yellow Wall,' and its vibrant home matches at Signal Iduna Park. Dortmund has a strong youth development system, producing talents like Marco Reus and Christian Pulisic. The club's attacking style of play, coupled with its commitment to entertaining football, has made it a fan favorite. Dortmund's rivalry with Bayern Munich, known as Der Klassiker, adds to the excitement of the Bundesliga, showcasing the fierce competition in German football."),

        FootballTeam("Arsenal", "https://yt3.googleusercontent.com/2yodAiZzMMdepud08lhluj2UKaD_3gkrsHXPlrOgSro6G26Rh5Z24qhhuuemKNCtMK6lcnhXFQ=s900-c-k-c0x00ffffff-no-rj", "Arsenal, founded in 1886, is one of the most successful clubs in English football, with 13 league titles and a rich history of legendary players like Thierry Henry and Dennis Bergkamp. Known for their attacking style, Arsenal has a passionate fan base and plays at the iconic Emirates Stadium. The club's rivalry with Tottenham, known as the North London Derby, adds to the excitement of the Premier League. Arsenal's commitment to youth development has produced numerous talents over the years. Despite recent challenges, the club continues to strive for success in domestic competitions and aims to return to the top of English football."),

        FootballTeam("Tottenham Hotspur", "https://m.media-amazon.com/images/M/MV5BZTEzZTdkN2UtNmE0OS00ZTZiLTk0YWEtZmQyNDQyNDE4NGVlXkEyXkFqcGdeQXVyMjUyNDk2ODc@._V1_.jpg", "Tottenham Hotspur, founded in 1882, has a rich history in English football with 2 league titles and a passionate fan base. The club plays at the Tottenham Hotspur Stadium, known for its modern design and vibrant atmosphere. Spurs are known for their attacking style of play and have produced several notable players, including Harry Kane and Gareth Bale. The club's fierce rivalry with Arsenal, known as the North London Derby, adds to the excitement of the Premier League. Tottenham continues to strive for success in domestic and European competitions, aiming to secure its first-ever UEFA Champions League title."),

        FootballTeam("Olympique Lyonnais", "https://lh3.googleusercontent.com/fxvNn5nTYdwc71NF-0tqom5oJ5EPCLQEfFwSWXXTEX_MV9ICIVIj8teCeOHcGkhqdzrHvWrt5YQ=w1440-ns-nd-rj", "Olympique Lyonnais, founded in 1950, is one of the most successful clubs in French football, with 7 Ligue 1 titles. The club is known for its strong youth academy, producing talents like Karim Benzema and Alexandre Lacazette. The Parc Olympique Lyonnais serves as a modern home for the team's passionate supporters. Lyon's commitment to attacking football and its rich heritage make it a formidable force in Ligue 1. The club has a growing presence in European competitions, aiming to compete with France's elite clubs. Lyon's consistent performances and dedication to development contribute to its status as a top club in French football."),

        FootballTeam("FC Porto", "https://i.pinimg.com/736x/35/8e/4d/358e4dec9a82fe5416741234bdd8d6b0.jpg", "Founded in 1893, FC Porto is one of the most successful clubs in Portuguese football, boasting 29 Primeira Liga titles and 2 UEFA Champions League trophies. The club is known for its strong youth academy, producing stars like Deco and James Rodríguez. Estádio do Dragão serves as a fortress for the club's passionate supporters. Porto's attacking style and commitment to excellence have made it a dominant force in domestic competitions. The club's fierce rivalry with Benfica adds to the excitement of Portuguese football. Porto aims to continue its legacy of success both in Portugal and on the European stage."),

        FootballTeam("Ajax", "https://avatars.mds.yandex.net/i?id=6b0c9fe903a352adf002d2ba394fca40_l-3707062-images-thumbs&n=13", "Founded in 1900, AFC Ajax is one of the most successful clubs in Dutch football, with 35 Eredivisie titles and 4 UEFA Champions League trophies. Known for its attacking style and famous youth academy, Ajax has produced legendary players like Johan Cruyff and Marco van Basten. Johan Cruyff Arena serves as a modern home for the club's passionate supporters. Ajax's commitment to attacking football and its rich heritage make it a formidable force in both domestic and European competitions. The club's rivalry with PSV Eindhoven adds to the excitement of Dutch football, showcasing the competitive nature of the Eredivisie."),

        FootballTeam("Roma", "https://avatars.mds.yandex.net/i?id=2811c717515296688da2fd446baea3bf_l-6846484-images-thumbs&n=13", "AS Roma, founded in 1927, is one of the most storied clubs in Italian football, known for its passionate fan base and historic successes, including 3 Serie A titles. The club has produced numerous legendary players, such as Francesco Totti, who became a symbol of the club. Stadio Olimpico serves as the vibrant home ground for Roma supporters. The club's fierce rivalry with Lazio, known as the Derby della Capitale, adds to the drama of Serie A. Roma continues to strive for success in both domestic and European competitions, aiming to secure its first UEFA Champions League title."),

        FootballTeam("Valencia", "https://avatars.dzeninfra.ru/get-zen_doc/1707291/pub_5ea71bac6135402f75338b51_5ea71d7eb14f910ab90b27d7/scale_1200", "Founded in 1919, Valencia CF is one of the prominent clubs in Spanish football, with 6 La Liga titles and 1 UEFA Champions League trophy. The club has a rich history of passionate supporters and a strong tradition. Mestalla Stadium is renowned for its vibrant atmosphere during matches. Valencia has produced several legendary players, including David Villa and Juan Mata. The club's fierce rivalry with Levante adds to the excitement of La Liga. Valencia continues to strive for success in domestic competitions, aiming to reclaim its place among Spain's elite clubs."),

        FootballTeam("Atletico Madrid", "https://i.pinimg.com/originals/b1/6b/b9/b16bb91c9677f435d8cdc8186fb1c569.jpg", "Founded in 1903, Atletico Madrid is known for its passionate fan base and competitive spirit. The club has won 11 La Liga titles and 3 UEFA Champions League titles, showcasing its prominence in Spanish football. Under the management of Diego Simeone, Atletico has developed a strong defensive style combined with quick counter-attacking play, making them a formidable opponent in domestic and European competitions. Their home ground, Wanda Metropolitano, offers an electrifying atmosphere during matches. Atletico's fierce rivalry with Real Madrid, known as the Madrid derby, adds to the excitement of La Liga."),
    )

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        binding = FragmentTeamsBinding.inflate(inflater, container, false)

        val adapter = TeamsAdapter(teams) { team ->
            showTeamHistoryDialog(team)
        }

        binding.recyclerViewTeams.adapter = adapter
        binding.recyclerViewTeams.layoutManager = LinearLayoutManager(requireContext())

        return binding.root
    }

    private fun showTeamHistoryDialog(team: FootballTeam) {
        val dialog = TeamHistoryDialogFragment.newInstance(team.name, team.history, team.logoUrl)
        dialog.show(parentFragmentManager, "TeamHistoryDialog")
    }
}
